---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 'https://api.stackbit.com/project/5e077925ae67b10019e54487/webhook/forestry'
sections:
  - type: document
    label: Global Site Config
    path: config.yaml
    templates:
      - config
  - type: document
    label: Header Configuration
    path: data/header.yml
    templates:
      - header
  - type: document
    label: Footer Configuration
    path: data/footer.yml
    templates:
      - footer
  - type: document
    label: Social Links
    path: data/social.json
    templates:
      - social
  - type: document
    label: Author
    path: data/author.json
    templates:
      - author
  - type: document
    label: Home
    path: content/_index.md
    templates:
      - home
  - type: directory
    path: content
    match: '**/*'
    exclude: '{posts/**,_index.md}'
    label: Page
    create: all
    templates:
      - page
  - type: directory
    path: content/posts
    match: '**/*'
    label: Post
    create: all
    templates:
      - post
upload_dir: static/images
public_path: /images
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
version: '0.47'
